# Generated by Django 3.2.4 on 2021-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='used_mileage',
            field=models.IntegerField(null=True),
        ),
    ]
